name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set environment (dev vs prod)
      - name: Set environment variables
        id: vars
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "ENV=prod" >> $GITHUB_OUTPUT
            echo "TAG=prod" >> $GITHUB_OUTPUT
          else
            echo "ENV=dev" >> $GITHUB_OUTPUT
            echo "TAG=dev" >> $GITHUB_OUTPUT
          fi

      # 3. Debug image name (helps troubleshooting)
      - name: Debug image name
        run: echo "Image = ghcr.io/karris12/${{ github.event.repository.name }}:${{ steps.vars.outputs.TAG }}"

      # 4. Login to GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: karris12
          password: ${{ secrets.CR_PAT }}

      # 5. Build & Push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/karris12/${{ github.event.repository.name }}:${{ steps.vars.outputs.TAG }}
            ghcr.io/karris12/${{ github.event.repository.name }}:${{ github.sha }}
            ghcr.io/karris12/${{ github.event.repository.name }}:latest

      # 6. Update GitOps repository
      - name: Update GitOps repository
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          rm -rf gitops
          git clone https://github.com/karris12/grade-api-gitops.git gitops
          cd gitops

          # Select environment file
          if [ "${{ steps.vars.outputs.ENV }}" = "prod" ]; then
            FILE="environments/prod/deployment.yaml"
          else
            FILE="environments/dev/deployment.yaml"
          fi

          IMAGE="ghcr.io/karris12/${{ github.event.repository.name }}:${{ steps.vars.outputs.TAG }}"

          echo "Updating image to $IMAGE in $FILE"

          # Replace image in YAML
          sed -i "s|image: .*|image: $IMAGE|" $FILE

          # Git config
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add $FILE

          # Only commit if changes exist
          if ! git diff --cached --quiet; then
            git commit -m "Update ${{ steps.vars.outputs.ENV }} image to ${{ steps.vars.outputs.TAG }}"
            git remote set-url origin https://${{ secrets.GITOPS_PAT }}@github.com/karris12/grade-api-gitops.git
            git push origin main
          else
            echo "No changes to commit"
          fi
