name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set environment (dev vs prod)
      - name: Set environment variables
        id: vars
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "ENV=prod" >> $GITHUB_OUTPUT
            echo "TAG=prod" >> $GITHUB_OUTPUT
          else
            echo "ENV=dev" >> $GITHUB_OUTPUT
            echo "TAG=dev" >> $GITHUB_OUTPUT
          fi

      # 3. Login to GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      # 4. Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 5. Build & Push Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.TAG }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      # 6. Update GitOps Repo
      - name: Update GitOps repository
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          rm -rf gitops
          git clone https://github.com/karris12/grade-api-gitops.git gitops
          cd gitops

          if [ "${{ steps.vars.outputs.ENV }}" = "prod" ]; then
            FILE="environments/prod/deployment.yaml"
          else
            FILE="environments/dev/deployment.yaml"
          fi

          sed -i "s|image: ghcr.io/${{ github.repository }}:.*|image: ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.TAG }}|" $FILE

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add $FILE
          git commit -m "Update ${{ steps.vars.outputs.ENV }} image to ${{ steps.vars.outputs.TAG }}"
          git push https://${{ secrets.GITOPS_PAT }}@github.com/karris12/grade-api-gitops.git main
          git add $FILE
          git commit -m "Update ${{ steps.vars.outputs.ENV }} image to ${{ steps.vars.outputs.TAG }}"
          git push https://${{ secrets.GITOPS_PAT }}@github.com/karris12/grade-api-gitops.git main
